# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('version', models.CharField(blank=True, max_length=32, null=True)),
                ('md5hash', models.CharField(blank=True, max_length=32, null=True)),
                ('metadata_ini', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField()),
                ('download_perm', models.CharField(default='@all', max_length=256)),
                ('edit_perm', models.CharField(default='@pkgmgr', max_length=256)),
            ],
        ),
    ]
