# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameauthorrole',
            name='symbolic_id',
            field=models.SlugField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gametag',
            name='symbolic_id',
            field=models.SlugField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gametagcategory',
            name='symbolic_id',
            field=models.SlugField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='urlcategory',
            name='symbolic_id',
            field=models.SlugField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='gametag',
            unique_together=set([('category', 'name')]),
        ),
    ]
