# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameauthorrole',
            name='symbolic_id',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
